### ISSUE TITLE
Missing Deps

### ISSUE THREAD

**Issue by xelerated** [MooseDojo/apt2#20]
When I fire it up there are a lot of missing Deps. responder, anonldp, nmapbasescan etc.... I havent seen anywhere to enable them, does that mean something on the OS is missing, or they just need activated?

**Comment by tatanus** [comment]
Those modules are most likely disabled because they are missing some dependencies.  The messages in red that show up at the top of the output when you run apt2 will state this.  They should also tell you the program or script that is missing.  If you install these programs, such as nmap or responder, or whatever the missing program or script is, those errors will disappear.  However, apt2 will still run without those modules, but you will not be getting the full capability of it until you install those dependencies.

**Comment by tatanus** [comment]
As i have heard nothing else on this issue, I will assume it is satisfied.
