### ISSUE TITLE
I have studied the command line arguments, but am still getting this error:

### ISSUE THREAD

**Issue by briqhaus** [MooseDojo/apt2#41]
I have tried both with --target for IP address, and with -f for *.xml output from nmap scan previously done. Would love to have this tool up and running for pentests, thanks.

*** print_exc:
Traceback (most recent call last):
  File "/usr/share/apt2/apt2", line 15, in main
    framework.run(sys.argv[1:])
  File "/usr/share/apt2/core/framework.py", line 725, in run
    _instance.go(file)
  File "/usr/share/apt2/core/inputModule.py", line 31, in go
    return self.process(inputfile)
  File "/usr/share/apt2/modules/input/nmaploadxml.py", line 14, in process
    n = mynmap(self.config, self.display)
  File "/usr/share/apt2/core/mynmap.py", line 19, in __init__
    self.nm = nmap.PortScanner()
AttributeError: 'module' object has no attribute 'PortScanner'

**Comment by briqhaus** [comment]
Please disregard, the project is running now, however I do have some missing stuff at the beginning I would like to address, and I do not know how to go about accomplishing this feat:

[!] Module 'apt2_shodan' disabled:
[!]      API key is missing
[!] Module 'searchnfsshare' disabled:
[!]      Module Manually Disabled !!!

**Comment by acompton-r7** [comment]
shodan_api requires you to get a shodan api key and set it in the config file for apt2.

responder will continue for approximately 5 minutes until it finally finishes.  This is by design and it is not just hanging.  the message you are saying is repeating is also by design.  that status message is set to display ever few seconds to give you a status of what modules are currently running.
