### ISSUE TITLE
Problems installing setup file

### ISSUE THREAD

**Issue by ctgreen78** [MooseDojo/apt2#49]
Hi, I am wondering if you can help me get APT2 running on the latest version of Kali. My Kali instance is fully updated/upgraded but I can't seem to get past these errors when trying to run the setup file. Any help would be appreciated. Thanks.

![apt2_install_errors](https://user-images.githubusercontent.com/34352828/36047993-c12d9e66-0dab-11e8-8b10-5295bf219dfd.JPG)

**Comment by Snifer** [comment]
Hi is necessary install Cython first!

`pip install cython. `

Regards,
Snifer

**Comment by ctgreen78** [comment]
That looked to have done the trick! Thanks Snifer!!

**Comment by acompton-r7** [comment]
just as an additional note....  you do not have to install APT2 to run it.  go to the directory where you did a github clone and type "python apt2.py" and include any command line arguments you wish.

additionally, I would just like to say that I am not 100% sure which of the modules are currently working as expected.  Due to changes in tool output and other items some of them may currently be broken.  I am working hard to get a new/improved/updated version od apt2 ready for release early in March.  Please stay tuned.  :-)
